os:
  - linux

services:
  - docker

before_install:
  - docker build  -t rmnlaiacona/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true rmnlaiacona/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: "docker-react-2"
  env: "DockerReact2-env"
  bucket_name: "elasticbeanstalk-us-east-1-631852783778"
  bucket_path: "docker-react-2"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
